# Generated by Django 3.1.3 on 2020-12-06 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128)),
                ('date_of_creating', models.DateField(auto_now_add=True)),
                ('personal_info', models.TextField()),
                ('foreign_language', models.CharField(choices=[('Английский', 'Английский'), ('Французский', 'Французский'), ('Немецкий', 'Немецкий')], default='Английский', max_length=32)),
                ('skills_list', models.TextField()),
                ('user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
