# Generated by Django 3.1.3 on 2020-12-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CVModel',
        ),
    ]
