# Generated by Django 3.1.3 on 2020-12-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cvmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvmodel',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='cvmodel',
            name='email',
        ),
        migrations.AlterField(
            model_name='cvmodel',
            name='position',
            field=models.CharField(max_length=128),
        ),
    ]
